#ifndef KEYWORD_TOKENS_H
#define KEYWORD_TOKENS_H

#define TOKEN_OPEN_PAREN 6
#define TOKEN_CLOSE_PAREN 7
#define TOKEN_DOUBLE_QUOTE 8
#define TOKEN_OPEN_SQUARE_BRACKET 9
#define TOKEN_KEYWORD_MODULE 8

#endif