#ifndef KEYWORD_TOKENS_H
#define KEYWORD_TOKENS_H

#define TOKEN_OPEN_PAREN 6
#define TOKEN_CLOSE_PAREN 7
#define TOKEN_DOUBLE_QUOTE 8
#define TOKEN_OPEN_SQUARE_BRACKET 9
#define TOKEN_EQUAL_SIGN 10
#define TOKEN_KEYWORD_MODULE 11
#define TOKEN_KEYWORD_I32 12
#define TOKEN_KEYWORD_I64 13
#define TOKEN_KEYWORD_F32 14
#define TOKEN_KEYWORD_F64 15
#define TOKEN_KEYWORD_TYPE 16
#define TOKEN_KEYWORD_PARAM 17
#define TOKEN_KEYWORD_RESULT 18

#endif

