#ifndef KEYWORD_TOKENS_H
#define KEYWORD_TOKENS_H

#define TOKEN_OPEN_PAREN 6
#define TOKEN_CLOSE_PAREN 7
#define TOKEN_DOUBLE_QUOTE 8
#define TOKEN_OPEN_SQUARE_BRACKET 9
#define TOKEN_EQUAL_SIGN 10
#define TOKEN_KEYWORD_MODULE 11
#define TOKEN_KEYWORD_I32 12
#define TOKEN_KEYWORD_I64 13
#define TOKEN_KEYWORD_F32 14
#define TOKEN_KEYWORD_F64 15
#define TOKEN_KEYWORD_TYPE 16
#define TOKEN_KEYWORD_PARAM 17
#define TOKEN_KEYWORD_RESULT 18
#define TOKEN_KEYWORD_IMPORT 19
#define TOKEN_KEYWORD_FUNC 20
#define TOKEN_KEYWORD_TABLE 21
#define TOKEN_KEYWORD_FUNCREF 22
#define TOKEN_KEYWORD_EXTERNREF 23
#define TOKEN_KEYWORD_MEMORY 24
#define TOKEN_KEYWORD_GLOBAL 25
#define TOKEN_KEYWORD_MUT 26
#define TOKEN_KEYWORD_EXPORT 27
#define TOKEN_KEYWORD_START 28
#define TOKEN_KEYWORD_ELEM 29
#define TOKEN_KEYWORD_DECLARE 30
#define TOKEN_KEYWORD_OFFSET 31
#define TOKEN_KEYWORD_ITEM 32
#define TOKEN_KEYWORD_EXTERN 33
#define TOKEN_KEYWORD_CODE 34
#define TOKEN_KEYWORD_LOCAL 35
#define TOKEN_KEYWORD_DATA 36
#define TOKEN_KEYWORD_NAME 37

#endif

